// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Entity.CalculoBasal", b =>
                {
                    b.Property<int>("CalculoBasalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CalculoBasalId");

                    b.ToTable("CalculosBasal");
                });

            modelBuilder.Entity("ApplicationCore.Entity.CaracterizacaoArea", b =>
                {
                    b.Property<int>("CaracterizacaoAreaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cidade");

                    b.Property<string>("DescricaoAmbiente");

                    b.Property<double>("TamanhoPropriedade");

                    b.Property<string>("TipoArea");

                    b.Property<string>("TipoClima");

                    b.Property<string>("TipoSolo");

                    b.HasKey("CaracterizacaoAreaId");

                    b.ToTable("CaracterizacoesAreas");
                });

            modelBuilder.Entity("ApplicationCore.Entity.ColetaAmostra", b =>
                {
                    b.Property<int>("ColetaAmostraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Armazenamento");

                    b.Property<DateTime>("DataColeta");

                    b.Property<double>("PesoAmostra");

                    b.Property<int>("Profundidade");

                    b.Property<bool>("Sazonalidade");

                    b.Property<int>("TempodeRepouso");

                    b.Property<string>("TipodeEcossistema");

                    b.Property<string>("TipodeTratamento");

                    b.HasKey("ColetaAmostraId");

                    b.ToTable("ColetasAmostras");
                });

            modelBuilder.Entity("ApplicationCore.Entity.MateriaisEquipamentos", b =>
                {
                    b.Property<int>("MateriaisEquipamentosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MateriaisUtilizados");

                    b.HasKey("MateriaisEquipamentosId");

                    b.ToTable("MateriaisEquipamentos");
                });

            modelBuilder.Entity("ApplicationCore.Entity.Pesquisador", b =>
                {
                    b.Property<int>("PesquisadorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InstituicaoDeEnsino");

                    b.Property<string>("Nome");

                    b.HasKey("PesquisadorId");

                    b.ToTable("Pesquisadores");
                });

            modelBuilder.Entity("ApplicationCore.Entity.ProcessamentoAmostra", b =>
                {
                    b.Property<int>("ProcessamentoAmostraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoProcedimento");

                    b.Property<int>("Peneira");

                    b.Property<DateTime>("PeriodoIncubacao");

                    b.Property<double>("Refrigeracao");

                    b.Property<string>("Solucoes");

                    b.Property<string>("TipodeArmazenamento");

                    b.HasKey("ProcessamentoAmostraId");

                    b.ToTable("ProcessamentoAmostras");
                });
#pragma warning restore 612, 618
        }
    }
}
